<?php

namespace BackSyst\SystemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RemoteMachineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemoteMachineRepository extends EntityRepository
{
}
